package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/lakshyab1995/tiger-kittens/db"
	"github.com/lakshyab1995/tiger-kittens/graph/model"
	"github.com/lakshyab1995/tiger-kittens/jwt"
)

// CreateUser is the resolver for the CreateUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, username string, password string, email string) (*model.User, error) {
	dbUser := &db.User{
		Username: username,
		Password: password,
		Email:    email,
		ID:       uuid.New().String(),
	}
	tokenModel, err := r.UserRepository.Create(dbUser)
	if err != nil {
		return nil, err
	}

	token := fmt.Sprintf("Bearer %s", tokenModel.Token)
	return &model.User{
		ID:       dbUser.ID,
		Username: dbUser.Username,
		Email:    dbUser.Email,
		Expiry:   &tokenModel.Expiry,
		Token:    &token,
	}, nil
}

// CreateTiger is the resolver for the createTiger field.
func (r *mutationResolver) CreateTiger(ctx context.Context, name string, dateOfBirth string, lastSeenTimestamp string, coordinates model.CoordinatesInput) (*model.Tiger, error) {
	panic(fmt.Errorf("not implemented: CreateTiger - createTiger"))
}

// CreateSighting is the resolver for the CreateSighting field.
func (r *mutationResolver) CreateSighting(ctx context.Context, tigerID int, timestamp string, coordinates model.CoordinatesInput, imageURL *string) (*model.Sighting, error) {
	panic(fmt.Errorf("not implemented: CreateSighting - CreateSighting"))
}

// Login is the resolver for the Login field.
func (r *mutationResolver) Login(ctx context.Context, input model.Login) (*model.TokenMeta, error) {
	var user db.User
	user.Password = input.Password
	user.Username = input.Username
	isAuthenticated := r.UserRepository.AuthenticateUser(user.Username, user.Password)
	if !isAuthenticated {
		return nil, &WrongUsernameOrPasswordError{}
	}
	token, err := jwt.GenerateToken(user.Username)
	if err != nil {
		return nil, err
	}
	return &model.TokenMeta{
		Token:  token.Token,
		Expiry: token.Expiry,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, token string) (*model.TokenMeta, error) {
	return RefreshToken(ctx, token)
}

// ListTigers is the resolver for the listTigers field.
func (r *queryResolver) ListTigers(ctx context.Context, first *int, after *string) (*model.TigerConnection, error) {
	panic(fmt.Errorf("not implemented: ListTigers - listTigers"))
}

// ListSightings is the resolver for the ListSightings field.
func (r *queryResolver) ListSightings(ctx context.Context, tigerID int, first *int, after *string) (*model.SightingConnection, error) {
	panic(fmt.Errorf("not implemented: ListSightings - ListSightings"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
